#!/usr/bin/env bash
# The first match in the $PATH environment variable.
# script that will display information about subdomains
my_sol() {
	if [ "$#" -eq 2 ]
	then
		dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -v x="$2" 'NR==2 {print "The subdomain "x" is a "$4" record and points to "$5"";}'
	elif [ "$#" -eq 1 ]
	then
		dig "www.$1" | awk '/ANSWER SECTION:/ {getline; print "The subdomain www is a "$4" record and points to "$5"";}'
		dig "lb-01.$1" | awk '/ANSWER SECTION:/ {getline; print "The subdomain lb-01 is a "$4" record and points to "$5"";}'
		dig "web-01.$1" | awk '/ANSWER SECTION:/ {getline; print "The subdomain web-01 is a "$4" record and points to "$5"";}'
		dig "web-02.$1" | awk '/ANSWER SECTION:/ {getline; print "The subdomain web-02 is a "$4" record and points to "$5"";}'
	fi
}
my_sol $1 $2
