#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

#sudo mkdir /etc/nginx/html
#sudo touch /etc/nginx/html/index.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > sudo /etc/nginx/sites-available/default

sudo service nginx restart
