#!/usr/bin/env bash
# shebang line - The first match in the $PATH environment variable.
sudo apt-get -y update
sudo apt-get -y install nginx
# ufw allow 'Nginx HTTP'
# ufw allow ssh
# ufw allow 'OpenSSH'
sudo echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
sudo service nginx restart
