#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y nginx

#sudo mkdir -p /var/www/html
#sudo touch /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
sudo touch /var/www/html/404.html
sudo echo "Page not found" > /var/www/html/404.html

sudo echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index index.html index.htm;
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
