#!/usr/bin/env bash
#shebang line - The first match in the $PATH environment variable.
# Bash script that uses ssh to connect to your server using
# the private key ~/.ssh/holberton with the user ubuntu.
ssh -i ~/.ssh/school ubuntu@54.237.113.148
